//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirst.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class cantidad
    {
        public int id { get; set; }
        public Nullable<int> cantidad1 { get; set; }
    }
}
